name: document_scanning
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  firebase_core: ^2.24.2
  firebase_ml_vision: ^0.12.0+3
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
