CREATE TABLE jeton_rafraichissements (
   identifiant_utilisateur VARCHAR2(50),
   jeton VARCHAR2(150) NOT NULL,
   PRIMARY KEY(identifiant_utilisateur),
   CONSTRAINT unique_jeton UNIQUE(jeton)
);

CREATE TABLE roles (
   id NUMBER,
   nom VARCHAR2(50) NOT NULL,
   niveau NUMBER NOT NULL,
   PRIMARY KEY(id),
   CONSTRAINT unique_nom_role UNIQUE(nom)
);

CREATE TABLE utilisateurs (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_role NUMBER NOT NULL,
   nom VARCHAR2(50) NOT NULL,
   prenom VARCHAR2(50),
   contact CHAR(10) NOT NULL,
   identifiant VARCHAR2(50) NOT NULL,
   mot_de_passe VARCHAR2(150) NOT NULL,
   etat NUMBER NOT NULL,
   PRIMARY KEY(id),
   CONSTRAINT unique_contact_utilisateur UNIQUE(contact),
   CONSTRAINT unique_identifiant_utilisateur UNIQUE(identifiant),
   FOREIGN KEY(id_role) REFERENCES roles(id)
);

CREATE TABLE election (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   nom VARCHAR2(50) UNIQUE NOT NULL,
   date_debut DATE NOT NULL,
   date_fin DATE,
   PRIMARY KEY(id)
);

CREATE TABLE resultats (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   code_bv VARCHAR2(12) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   etat NUMBER NOT NULL,
   PRIMARY KEY(id),
   CONSTRAINT unique_resultat UNIQUE(id_election, code_bv),
   FOREIGN KEY(id_election) REFERENCES election(id)
);

CREATE TABLE details_resultats (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   resultat_id NUMBER NOT NULL,
   nom_candidat VARCHAR2(50) NOT NULL,
   parti_politique VARCHAR2(50) NOT NULL,
   chemin_photo VARCHAR2(150),
   voix NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(resultat_id) REFERENCES resultats(id),
   CONSTRAINT unique_resultat_candidat UNIQUE(resultat_id, nom_candidat, parti_politique)
);