CREATE TABLE resultats_provisoires_par_bv (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_bv NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100),
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_bv) REFERENCES bv(id),
   CONSTRAINT unique_resultat_provisoire UNIQUE(id_election, id_bv, numero_candidat)
);
CREATE TABLE resultats_statistiques_provisoires_par_bv (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_bv NUMBER NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   exprimes NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_bv) REFERENCES bv(id),
   CONSTRAINT unique_resultat_statistique_provisoire UNIQUE(id_election, id_bv)
);

CREATE TABLE resultats_provisoires_par_fokontany (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_fokontany NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100),
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_fokontany) REFERENCES fokontany(id),
   CONSTRAINT unique_resultat_provisoire UNIQUE(id_election, id_fokontany, numero_candidat)
);
CREATE TABLE resultats_statistiques_provisoires_par_fokontany (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_fokontany NUMBER NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   exprimes NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_fokontany) REFERENCES fokontany(id),
   CONSTRAINT unique_resultat_statistique_provisoire UNIQUE(id_election, id_fokontany)
);