CREATE TABLE resultats_statistiques_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   code_bv VARCHAR2(12) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL
);

CREATE TABLE resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_bv VARCHAR2(12) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   CONSTRAINT unique_resultat_provisoire UNIQUE(id_election, code_bv)
);