CREATE TABLE bv_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_bv NUMBER NOT NULL,
   code_bv CHAR(12) NOT NULL,
   nom_bv VARCHAR2(50) NOT NULL,
   nom_fokontany VARCHAR2(50) NOT NULL,
   nom_commune VARCHAR2(50) NOT NULL,
   nom_district VARCHAR2(50) NOT NULL,
   nom_region VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   nom_operateur VARCHAR2(50),
   prenom_operateur VARCHAR2(50),
   contact_operateur CHAR(10),
   nom_membre_bv VARCHAR2(50),
   prenom_membre_bv VARCHAR2(50),
   contact_membre_bv CHAR(10),
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_bv) REFERENCES bv(id),
   CONSTRAINT unique_bv_resultat_provisoire UNIQUE(id_election, id_bv)
);
CREATE TABLE bv_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES bv_resultats_provisoires(id),
   CONSTRAINT unique_bv_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


CREATE TABLE fokontany_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_fokontany NUMBER NOT NULL,
   code_fokontany CHAR(8) NOT NULL,
   nom_fokontany VARCHAR2(50) NOT NULL,
   nom_commune VARCHAR2(50) NOT NULL,
   nom_district VARCHAR2(50) NOT NULL,
   nom_region VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_fokontany) REFERENCES fokontany(id),
   CONSTRAINT unique_fokontany_resultat_provisoire UNIQUE(id_election, id_fokontany)
);
CREATE TABLE fokontany_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES fokontany_resultats_provisoires(id),
   CONSTRAINT unique_fokontany_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


CREATE TABLE communes_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_commune NUMBER NOT NULL,
   code_commune CHAR(6) NOT NULL,
   nom_commune VARCHAR2(50) NOT NULL,
   nom_district VARCHAR2(50) NOT NULL,
   nom_region VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_commune) REFERENCES communes(id),
   CONSTRAINT unique_commune_resultat_provisoire UNIQUE(id_election, id_commune)
);
CREATE TABLE communes_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES communes_resultats_provisoires(id),
   CONSTRAINT unique_commune_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


-- municipalite = commune, only for local election
CREATE TABLE municipalites_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_municipalite NUMBER NOT NULL,
   code_municipalite CHAR(6) NOT NULL,
   nom_municipalite VARCHAR2(50) NOT NULL,
   nom_district VARCHAR2(50) NOT NULL,
   nom_region VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_municipalite) REFERENCES municipalites(id),
   CONSTRAINT unique_municipalite_resultat_provisoire UNIQUE(id_election, id_municipalite)
);
CREATE TABLE municipalites_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES municipalites_resultats_provisoires(id),
   CONSTRAINT unique_municipalite_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


-- presidential and legislative election only
CREATE TABLE districts_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_district NUMBER NOT NULL,
   code_district CHAR(4) NOT NULL,
   nom_district VARCHAR2(50) NOT NULL,
   nom_region VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_district) REFERENCES districts(id),
   CONSTRAINT unique_district_resultat_provisoire UNIQUE(id_election, id_district)
);
CREATE TABLE districts_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES districts_resultats_provisoires(id),
   CONSTRAINT unique_district_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


-- presidential election only
CREATE TABLE regions_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_region NUMBER NOT NULL,
   code_region CHAR(2) NOT NULL,
   nom_region VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_region) REFERENCES regions(id),
   CONSTRAINT unique_region_resultat_provisoire UNIQUE(id_election, id_region)
);
CREATE TABLE regions_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES regions_resultats_provisoires(id),
   CONSTRAINT unique_region_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


-- presidential election only
CREATE TABLE provinces_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   id_province CHAR(1) NULL,
   nom_province VARCHAR2(50) NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   FOREIGN KEY(id_province) REFERENCES provinces(id),
   CONSTRAINT unique_province_resultat_provisoire UNIQUE(id_election, id_province)
);
CREATE TABLE provinces_details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES provinces_resultats_provisoires(id),
   CONSTRAINT unique_province_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);


-- presidential election only
CREATE TABLE resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_election NUMBER NOT NULL,
   inscrits NUMBER NOT NULL,
   blancs NUMBER NOT NULL,
   nuls NUMBER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_election) REFERENCES elections(id),
   CONSTRAINT unique_resultat_provisoire UNIQUE(id_election)
);
CREATE TABLE details_resultats_provisoires (
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
   id_resultat_provisoire NUMBER NOT NULL,
   numero_candidat NUMBER NOT NULL,
   information_candidat VARCHAR2(100) NOT NULL,
   nom_entite_politique VARCHAR2(50) NOT NULL,
   description_entite_politique VARCHAR2(100) NOT NULL,
   voix_candidat NUMBER NOT NULL,
   chemin_photo_candidat VARCHAR2(100),
   PRIMARY KEY(id),
   FOREIGN KEY(id_resultat_provisoire) REFERENCES resultats_provisoires(id),
   CONSTRAINT unique_details_resultat_provisoire UNIQUE(id_resultat_provisoire, numero_candidat)
);